<a href="https://colab.research.google.com/github/Sreenavya04/AIML/blob/main/unit_6_%5B2-09-2024%5D%20neural%20network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
inputs=[1,2,3]
weights=[0.2,0.3,-0.5]
bias=2
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

#2)
inputs=[0.4,0.3,1,0.8]
weights1=[0.3,0.2,0.1,0.4]
weights2=[0.4,0.1,-0.1,0.2]
weights3=[0.2,-0.2,-0.1,0.8]
bias1=0.5
bias2=0.3
bias3=0.6
output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output)

#3)
import numpy as np
inputs=np.array([0.4,0.3,1,0.8])
weights=np.array([
    [0.3,0.2,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
])
biases=np.array([2,3,0.5])
output=np.dot(weights,inputs)+biases
print(output)
#with using def
def relu(x):
  return np.maximum(0,x)
  inputs=np.array([0.4,0.3,1,0.8])
weights=np.array([
    [0.3,0.2,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
])
biases=np.array([2,3,0.5])
output=np.dot(weights,inputs)+biases
output=relu(output)
print(output)

import numpy as np

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def relu(x):
  return np.maximum(0,x)

inputs = np.array([0.4, 0.3, 1, 0.8])
weights = np.array([
    [0.3, 0.2, 0.1, 0.4],
    [0.4, 0.1, -0.1, 0.2],
    [0.2, -0.2, -0.1, 0.8]
])
biases = np.array([0.5, 0.3, 0.6])

output = relu(np.dot(weights, inputs) + biases)
#Activation ReLU activation function
output1=relu(output)
print(output1)
output2=sigmoid(output)
print(output2)




1.3
[1.1, 0.55, 1.1600000000000001]
[2.48  2.787 1.181]
[2.48  2.787 1.181]
[1.1  0.55 1.16]
[0.75026011 0.63413559 0.76133271]
